-- ============================================================
-- V1.0__Init.sql - Criação das tabelas
-- ============================================================

CREATE TABLE tb_category (
                             id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             name VARCHAR(50) NOT NULL,
                             PRIMARY KEY (id)
);

CREATE TABLE tb_product (
                            id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            name             VARCHAR(100)   NOT NULL,
                            description      VARCHAR(1024)  NOT NULL,
                            price            DOUBLE         NOT NULL,
                            image            VARCHAR(255),
                            installment_info VARCHAR(100),
                            category_id      BIGINT,
                            content_type     VARCHAR(50),
                            image_name       VARCHAR(255),
                            PRIMARY KEY (id)
);

CREATE TABLE product_specifications (
                                        product_id    BIGINT       NOT NULL,
                                        specification VARCHAR(255) NOT NULL
);

CREATE TABLE product_gallery (
                                 product_id BIGINT       NOT NULL,
                                 image_url  VARCHAR(255) NOT NULL
);

CREATE TABLE tb_user (
                         id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         display_name VARCHAR(255),
                         password     VARCHAR(255),
                         username     VARCHAR(255),
                         provider     VARCHAR(255),
                         PRIMARY KEY (id)
);

CREATE TABLE tb_authority (
                              id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              authority VARCHAR(255),
                              PRIMARY KEY (id)
);

CREATE TABLE tb_user_authorities (
                                     user_id      BIGINT NOT NULL,
                                     authority_id BIGINT NOT NULL,
                                     PRIMARY KEY (user_id, authority_id)
);

CREATE TABLE tb_address (
                            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            user_id     BIGINT,
                            city        VARCHAR(100),
                            logradouro  VARCHAR(255),
                            numero      VARCHAR(20),
                            bairro      VARCHAR(100),
                            complemento VARCHAR(255),
                            cep         VARCHAR(10),
                            title       VARCHAR(100),
                            PRIMARY KEY (id)
);

CREATE TABLE tb_order (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          data           TIMESTAMP,
                          freight        DECIMAL(10, 2),
                          payment_method VARCHAR(50),
                          status         VARCHAR(30) NOT NULL DEFAULT 'AGUARDANDO_PAGAMENTO',
                          user_id        BIGINT,
                          address_id     BIGINT,
                          PRIMARY KEY (id)
);

CREATE TABLE tb_order_itens (
                                id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                order_id   BIGINT,
                                product_id BIGINT,
                                quantity   DOUBLE         NOT NULL,
                                unit_price DECIMAL(10, 2) NOT NULL,
                                PRIMARY KEY (id)
);

-- ============================================================
-- FOREIGN KEYS
-- ============================================================

ALTER TABLE tb_product
    ADD CONSTRAINT FK_Category_Product
        FOREIGN KEY (category_id) REFERENCES tb_category (id);

ALTER TABLE product_specifications
    ADD CONSTRAINT FK_Specifications_Product
        FOREIGN KEY (product_id) REFERENCES tb_product (id);

ALTER TABLE product_gallery
    ADD CONSTRAINT FK_Gallery_Product
        FOREIGN KEY (product_id) REFERENCES tb_product (id);

ALTER TABLE tb_user_authorities
    ADD CONSTRAINT FK_User_Authority
        FOREIGN KEY (user_id) REFERENCES tb_user (id);

ALTER TABLE tb_user_authorities
    ADD CONSTRAINT FK_Authority_User
        FOREIGN KEY (authority_id) REFERENCES tb_authority (id);

ALTER TABLE tb_address
    ADD CONSTRAINT FK_Address_User
        FOREIGN KEY (user_id) REFERENCES tb_user (id);

ALTER TABLE tb_order
    ADD CONSTRAINT FK_Order_User
        FOREIGN KEY (user_id) REFERENCES tb_user (id);

ALTER TABLE tb_order
    ADD CONSTRAINT FK_Order_Address
        FOREIGN KEY (address_id) REFERENCES tb_address (id);

ALTER TABLE tb_order_itens
    ADD CONSTRAINT FK_OrderItens_Order
        FOREIGN KEY (order_id) REFERENCES tb_order (id);

ALTER TABLE tb_order_itens
    ADD CONSTRAINT FK_OrderItens_Product
        FOREIGN KEY (product_id) REFERENCES tb_product (id);

ALTER TABLE tb_order
    ADD COLUMN comprovante_pdf VARCHAR(255);